#' @name Draw_AUC
#' @title plot on object generated by pROC::roc
#'
#' @details plot on AUC
#'
#' @param rocobj an object generated by pROC::roc
#' @param title title of the plot
#' @export
#'
#'
#'
library(tidyverse)
library(pROC)
library(stringi)
library(magrittr)
Draw_AUC = function(rocobj, title){
  cutOffPoint <- coords(rocobj, "best")
  if(dim(cutOffPoint)[1] > 1) cutOffPoint = cutOffPoint[1,]
  cutOffPointText <- paste0(round(cutOffPoint[1],3),"(",round(cutOffPoint[2],3),",",round(cutOffPoint[3],3),")")
  auc_res<-auc(rocobj)[1] # 计算AUC值
  auc_low<-ci(rocobj,of="auc")[1]
  auc_high<-ci(rocobj,of="auc")[3]

  ciobj <- ci.se(rocobj,specificities=seq(0, 1, 0.01))
  data_ci<-ciobj[1:101,1:3]
  data_ci<-as.data.frame(data_ci)
  x=as.numeric(rownames(data_ci))
  data_ci<-data.frame(x,data_ci)

  #绘图
  {
    AUS_line = ggroc(rocobj,
                     color="red",
                     size=1,
                     legacy.axes = F # FALSE时 横坐标为1-0 specificity；TRUE时 横坐标为0-1 1-specificity
    )+
      theme_classic()+
      geom_segment(aes(x = 1, y = 0, xend = 0, yend = 1),        # 绘制对角线
                   colour='grey',
                   linetype = 'dotdash'
      ) +
      geom_ribbon(data = data_ci,                                # 绘制置信区间
                  aes(x=x,ymin=X2.5.,ymax=X97.5.),               # 当legacy.axes=TRUE时， 把x=x改为x=1-x
                  fill = 'lightblue',
                  alpha=0.5)+
      geom_point(aes(x = cutOffPoint[[2]],y = cutOffPoint[[3]]))+ # 绘制临界点/阈值
      geom_text(size = 3,aes(x = cutOffPoint[[2]],y = cutOffPoint[[3]],
                             label=cutOffPointText),vjust=-1,check_overlap = T) + # 添加临界点/阈值文字标签
      labs(title = title,
           subtitle =stri_join("AUC = ", round(auc_res, 2) )) +
      theme(plot.title = element_text(hjust = 0.5),
            plot.subtitle = element_text(hjust = 0.5))
    plot(AUS_line)

  }
  return(AUS_line)
}
