#' @name Four_fold_rocobj
#' @title for a contructed rocobj, add Sensitivity, NPV, accuracy, etc. following the four-fold table
#'
#' @details for a contructed rocobj, add Sensitivity, NPV, accuracy, etc. following the four-fold table
#'
#' @param rocobj a rocobj generated by a dataframe, colnames as(c("Predict", "True")), Predict has c("Negative", "Positive"), True has c("Ctrl", "Disease")
#' @export
#'
#'
#'
library(magrittr)
library(tidyverse)
library(pROC)
Four_fold_rocobj = function(rocobj){
  cutOffPoint <- coords(rocobj, "best")[1] %>% as.numeric()
  if(rocobj$direction == "<"){
    Four_fold = data.frame(predict = c(rocobj$cases > cutOffPoint, rocobj$controls > cutOffPoint) %>% as.numeric(),
                           true = c(rep(1,length(rocobj$cases)), rep(0,length(rocobj$controls))))
  }else if(rocobj$direction == ">"){
    Four_fold = data.frame(predict = c(rocobj$cases < cutOffPoint, rocobj$controls < cutOffPoint) %>% as.numeric(),
                           true = c(rep(1,length(rocobj$cases)), rep(0,length(rocobj$controls))))

  }

  Four_fold = Four_fold %>%
    set_colnames(c("Predict", "True")) %>%
    mutate(Predict = mutate_list(Predict, c(0,1), c("Negative", "Positive"))) %>%
    mutate(True = mutate_list(True, c(0,1), c("Ctrl", "Disease"))) %>%
    table %>%
    cbind(apply(., 1, sum)) %>%
    rbind(apply(., 2, sum)) %>%
    set_colnames(c(colnames(.)[1:2], "Sum")) %>%
    set_rownames(c(rownames(.)[1:2], "Sum"))
  New_Four_fold = rbind(Four_fold,
                        data.frame(Ctrl = "", Disease = "", Sum = "", row.names = ""),
                        data.frame(Ctrl = (Four_fold[2,2]/Four_fold[3,2]) %>% round(4), Disease = "", Sum = "", row.names = "Sensitivity"),
                        data.frame(Ctrl = (Four_fold[1,1]/Four_fold[3,1]) %>% round(4), Disease = "", Sum = "", row.names = "Specificity"),
                        data.frame(Ctrl = (Four_fold[2,2]/Four_fold[2,3]) %>% round(4), Disease = "", Sum = "", row.names = "PPV"),
                        data.frame(Ctrl = (Four_fold[1,1]/Four_fold[1,3]) %>% round(4), Disease = "", Sum = "", row.names = "NPV"),
                        data.frame(Ctrl = ((Four_fold[1,1] + Four_fold[2,2])/Four_fold[3,3])%>% round(4), Disease = "", Sum = "", row.names = "Accuracy"),
                        data.frame(Ctrl = cutOffPoint %>% round(4), Disease = "", Sum = "", row.names = "Cut-off"),
                        data.frame(Ctrl = auc(rocobj) %>% round(4), Disease = "", Sum = "", row.names = "AUC")
  )
  return(New_Four_fold)
}
